FROM docker.io/almalinux/9-minimal

RUN microdnf update -y
# Install EPEL Repo
RUN microdnf install -y ImageMagick ImageMagick-devel espeak-ng python3-pip mariadb mariadb-server mariadb-devel nginx rsync ffmpeg-free 
